name: ESP32 Robot Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  esp32-test:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Python
        run: python --version

      - name: Install Python Packages
        run: |
          pip install robotframework
          pip install pyserial
          pip install amqtt

      - name: Start MQTT Broker
        shell: powershell
        run: |
          Start-Process python -ArgumentList "mqtt_server.py"

      - name: Wait for Broker
        run: Start-Sleep -Seconds 5

      - name: Run Robot Tests
        run: robot mqtt_test.robot

      - name: Upload Robot Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: |
            report.html
            log.html
            output.xml
