name: ESP32 Robot Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  esp32-test:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Python
        run: python --version

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install pyserial
          pip install amqtt

      - name: Start MQTT Broker
        run: |
          start /B python mqtt_server.py

      - name: Wait for broker
        run: timeout /t 5

      - name: Run Robot Tests
        run: robot mqtt_test.robot

      - name: Upload Robot Report
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: |
            report.html
            log.html
            output.xml
